Now Method calls work in feval, and porting it to peval would be just streight forward

diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,11 +1,10 @@
-#!/bin/sh
+#!/bin/bash
 
 # Copyright (c) <2013>, Amanj Sherwany <http://www.amanj.me>
 # All rights reserved.
 # A simple shell script, to automatically build the project and test it
 
 function help() {
-  usage
   line1="\nThis is a small shell script, to automatically build the project "
   line2="(plugin) and test the plugin (against the provided test file (case))"
   line3="\nCopyright (c) <2013>, Amanj Sherwany <http://www.amanj.me>\n"
@@ -13,12 +12,12 @@ function help() {
   echo ${line1}${line2}${line3}${line4}
 }
 function usage() {
-  echo "Usage: sudo [options] ./test TEST_FILE"
+  echo "Usage: ./test [options] TEST_FILE"
   echo "[options] are optional, and they can be one of the following:"
-  echo "-h | --help to print this help message."
-  echo "-c | --compile to recompile and repackage the plugin."
-  echo "-r | --run to run the test case, after compiling it.\n"
-  echo "-a | --all to compile all test cases, without running them.\n"
+  echo "-h to print this help message."
+  echo "-c to recompile and repackage the plugin."
+  echo "-r to run the test case, after compiling it.\n"
+  echo "-a to compile all test cases, without running them.\n"
   echo "Do not write the .scala extension for the test program."
 }
 
@@ -32,19 +31,39 @@ fi
 compile=false
 run=false
 testAll=false
+helpf=false
 
-while [[ $1 == -* ]]; do
-    case "$1" in
-      -h|--help) help; exit 0;;
-      -c|--compile) compile=true; shift;;
-      -r|--run) run=true;shift;;
-      -a|--all) testAll=true;shift;;
-      --) shift; break;;
-      -*) echo "invalid option: $1" 1>&2; usage; exit 1;;
-    esac
+while getopts ":h:c:r:a" OPTION;
+do
+  case $OPTION in
+    h) 
+      usage; 
+      helpf=true;
+      >&2
+      ;;
+    c) 
+      compile=true; 
+      >&2
+      ;;
+    r) 
+      run=true;
+      >&2
+      ;;
+    a)
+      testAll=true;
+      >&2
+      ;;
+    \?) echo "invalid option: $OPTION" 1>&2; usage;
+  exit 1;;
+  esac
 done
 
-file=${1}
+if [ ${helpf} == true ]; then
+  help
+  exit 0
+fi
+
+file=${@: -1}
 
 if [ ${testAll} == false ]; then
   if [[ ${file} == -* ]]; then
@@ -63,7 +82,6 @@ if [ ${compile} == true ]; then
   echo "   Compiling the plugin"
   echo "==========================="
   sbt package
-  wait
 fi
 
 echo "==========================="
@@ -83,14 +101,12 @@ testDest=${base}"plugin"
 # Create a destination direcotry if there is not one
 mkdir -p ${testDest}
 scalac -d ${testDest} -cp ${mina} -Xplugin:${mina} ${testFile}
-wait
 
 # Then compile it without the plugin
 plainDest=${base}"plain"
 # Create a destination direcotry if there is not one
 mkdir -p ${plainDest}
 scalac -d ${plainDest} -cp ${mina} ${testFile}
-wait
 
 if [ ${testAll} == false -a ${run} == true ]; then
   echo "==========================="
@@ -98,11 +114,9 @@ if [ ${testAll} == false -a ${run} == true ]; then
   echo "==========================="
   # Run the file once wihtout applying HPE
   scala -cp ${plainDest}:${mina} ${file}
-  wait
-
+  
   # Run the same file this time with applying HPE
   scala -cp ${testDest}:${mina} ${file}
-  wait
 fi
 
 exit 0
